### ISSUE TITLE
Current osclass build is outdated and unsupported.

### ISSUE THREAD

**Issue by navjottomer** [bitnami/bitnami-docker-osclass#36]
**Description**
Current osclass build is outdated and unsupported as the original project is dead. Osclass itself depend on osclass.org which is also down since September 2019.

Development is shifted now to this repository https://github.com/navjottomer/Osclass/
You can find the latest release at https://github.com/navjottomer/Osclass/releases

**Comment by sameersbn** [comment]
@navjottomer Thanks for letting us know about the status of the osclass project. I am creating an internal task to consider switching over to the new repo. Will we get in touch with you if we have any questions.
