### ISSUE TITLE
send email

### ISSUE THREAD

**Issue by rbatata** [bitnami/bitnami-docker-osclass#38]
Hello,

i´m using this with helm chart in openshift, all is working fine, but i cannot configure the smtp

I try i think everything, with environment variable, in backend, with and without authentication.

If i not fill the user and password i have a error in console "sh: 1: /usr/sbin/sendmail: not found", with the user and password i dont have this error.

I really need some help how to fix this.

Thanks

**Comment by miguelaeh** [comment]
Hi @rbatata ,
Could you share your SMTP configuration and the chart version you are using, please?
If you are configuring an external SMTP server it should not try to use sendmail

**Comment by rbatata** [comment]
hello, this is what i have:
![image](https://user-images.githubusercontent.com/72514432/133575777-88277f87-1758-4a46-ac2a-1e829ada0be1.png)

![image](https://user-images.githubusercontent.com/72514432/133576181-b910a4ec-925c-4768-93ae-828a0f859223.png)

thanks

**Comment by miguelaeh** [comment]
Hi @rbatata ,
which kind of external server are you using? Have in mind some services like Gmail block the mails unless you configure it to allow sending them.

**Comment by rbatata** [comment]
Hi,

My server is internal based on exchange.

**Comment by miguelaeh** [comment]
Hi @rbatata ,
Can you see any sending attempts in the email server logs?

**Comment by rbatata** [comment]
Hello,

I have this on my email server,

2021-09-14T14:28:09.133Z,server.local.example\Full_Relay_server.local.example,08D961D026F534D8,2, xx.xxx.xxx.xxx:25,xx.xxx.xxx.xxx:47188,<,EHLO example.mail.local,
2021-09-14T14:28:09.133Z,server.local.example\Full_Relay_server.local.example,08D961D026F534D8,3,10.164.212.131:25,10.164.212.200:47188,>,250 server.local.example Hello [xx.xxx.xxx.xxx] SIZE 12582912 PIPELINING DSN ENHANCEDSTATUSCODES 8BITMIME BINARYMIME CHUNKING,
2021-09-14T14:28:09.159Z,server.local.example\Full_Relay_server.local.example,08D961D026F534D8,4,10.164.212.131:25,10.164.212.200:47188,<,QUIT,

thanks

**Comment by miguelaeh** [comment]
Hi @rbatata ,
If your mail server is receiving the request it should not be an issue with the image. I recommend you to ask on the oscclass community forum or to re-check your mail server configuration.

**Comment by miguelaeh** [comment]
Hi @rbatata ,
did you test your configuration with a different public SMTP server?

**Comment by rbatata** [comment]
no, with public smtp i cannot test.

But i have a lot of other apps working without any problems with the same configs.

**Comment by rbatata** [comment]
hello,

you are talking about this file /bitnami/osclass/config.php ? If yes, no only have settings related with database

**Comment by carrodher** [comment]
The SMTP configuration is not stored in any configuration file but in the database, this is done [here](https://github.com/bitnami/bitnami-docker-osclass/blob/b93ef14bc85bcedbc28a7d4157174f6f8d7c0ddd/4/debian-10/rootfs/opt/bitnami/scripts/libosclass.sh#L161):

```bash
        # SMTP configuration tweaking the System Settings via Database
        # Based on https://docs.osclasspoint.com/setting-up-a-mail-server
        if ! is_empty_value "$OSCLASS_SMTP_HOST"; then
            local -a mysql_execute_args=("$OSCLASS_DATABASE_HOST" "$OSCLASS_DATABASE_PORT_NUMBER" "$OSCLASS_DATABASE_NAME" "$OSCLASS_DATABASE_USER" "$OSCLASS_DATABASE_PASSWORD")
            info "Configuring SMTP"
            settings_to_update=(
                "mailserver_auth=1"
                "mailserver_pop=0"
                "mailserver_host=${OSCLASS_SMTP_HOST}"
                "mailserver_port=${OSCLASS_SMTP_PORT_NUMBER}"
                "mailserver_username=${OSCLASS_SMTP_USER}"
                "mailserver_mail_from=${OSCLASS_EMAIL}"
                "mailserver_password=${OSCLASS_SMTP_PASSWORD}"
                "mailserver_ssl=${OSCLASS_SMTP_PROTOCOL}"
            )

            for setting in "${settings_to_update[@]}"; do
                # We split the key and value with the '=' delimiter via native Bash functionality to simplify the logic
                mysql_remote_execute "${mysql_execute_args[@]}" <<<"UPDATE oc_t_preference SET s_value='${setting#*=}' WHERE s_name='${setting%=*}';"
            done
        fi
```

Can you check in the database if those values are properly set?
